In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HousePricePrediction.csv')

In [3]:
df.head()

Id  MSSubClass MSZoning  LotArea LotConfig BldgType  OverallCond  \
0   0          60       RL     8450    Inside     1Fam            5   
1   1          20       RL     9600       FR2     1Fam            8   
2   2          60       RL    11250    Inside     1Fam            5   
3   3          70       RL     9550    Corner     1Fam            5   
4   4          60       RL    14260       FR2     1Fam            5   

   YearBuilt  YearRemodAdd Exterior1st  BsmtFinSF2  TotalBsmtSF  SalePrice  
0       2003          2003     VinylSd         0.0        856.0   208500.0  
1       1976          1976     MetalSd         0.0       1262.0   181500.0  
2       2001          2002     VinylSd         0.0        920.0   223500.0  
3       1915          1970     Wd Sdng         0.0        756.0   140000.0  
4       2000          2000     VinylSd         0.0       1145.0   250000.0

In [4]:
df.drop('Id', axis = 1, inplace = True)

In [5]:
df.drop('MSZoning', axis = 1, inplace = True)

In [6]:
df.head()

MSSubClass  LotArea LotConfig BldgType  OverallCond  YearBuilt  \
0          60     8450    Inside     1Fam            5       2003   
1          20     9600       FR2     1Fam            8       1976   
2          60    11250    Inside     1Fam            5       2001   
3          70     9550    Corner     1Fam            5       1915   
4          60    14260       FR2     1Fam            5       2000   

   YearRemodAdd Exterior1st  BsmtFinSF2  TotalBsmtSF  SalePrice  
0          2003     VinylSd         0.0        856.0   208500.0  
1          1976     MetalSd         0.0       1262.0   181500.0  
2          2002     VinylSd         0.0        920.0   223500.0  
3          1970     Wd Sdng         0.0        756.0   140000.0  
4          2000     VinylSd         0.0       1145.0   250000.0

In [7]:
df.isnull().sum()

MSSubClass         0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [8]:
df.isnull().mean()*100

MSSubClass       0.000000
LotArea          0.000000
LotConfig        0.000000
BldgType         0.000000
OverallCond      0.000000
YearBuilt        0.000000
YearRemodAdd     0.000000
Exterior1st      0.034258
BsmtFinSF2       0.034258
TotalBsmtSF      0.034258
SalePrice       49.982871
dtype: float64

In [9]:
df['LotConfig']. value_counts()
df['BldgType']. value_counts()
# df['Exterior1st']. value_counts()


BldgType
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: count, dtype: int64

In [10]:
df.isnull().sum()

MSSubClass         0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [11]:
df.fillna(method = 'bfill', inplace = True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_4912\3982322604.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill', inplace = True)


In [12]:
df.isnull().sum()

MSSubClass         0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        0
BsmtFinSF2         0
TotalBsmtSF        0
SalePrice       1459
dtype: int64

In [13]:
X = df[['MSSubClass','LotArea','LotConfig','BldgType','OverallCond','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']]
X.head()

MSSubClass  LotArea LotConfig BldgType  OverallCond  YearBuilt  \
0          60     8450    Inside     1Fam            5       2003   
1          20     9600       FR2     1Fam            8       1976   
2          60    11250    Inside     1Fam            5       2001   
3          70     9550    Corner     1Fam            5       1915   
4          60    14260       FR2     1Fam            5       2000   

   YearRemodAdd Exterior1st  BsmtFinSF2  TotalBsmtSF  
0          2003     VinylSd         0.0        856.0  
1          1976     MetalSd         0.0       1262.0  
2          2002     VinylSd         0.0        920.0  
3          1970     Wd Sdng         0.0        756.0  
4          2000     VinylSd         0.0       1145.0

In [14]:
y = df['SalePrice']
y.head()

0    208500.0
1    181500.0
2    223500.0
3    140000.0
4    250000.0
Name: SalePrice, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [16]:
print('X_train: ',X_train.shape)
print('X_test: ',X_test.shape)
print('y_train: ',y_train.shape)
print('y_test: ',y_test.shape)


X_train:  (2335, 10)
X_test:  (584, 10)
y_train:  (2335,)
y_test:  (584,)


In [17]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_Area = si.fit_transform(X_train[['LotArea']])
X_test_Area = si.fit_transform(X_test[['LotArea']])

In [18]:
X_train_Area

array([[18030.],
       [12919.],
       [ 3180.],
       ...,
       [ 2308.],
       [33983.],
       [ 9600.]])

In [19]:
X_test_Area

array([[ 8520.],
       [ 8088.],
       [ 9842.],
       [16451.],
       [ 9742.],
       [ 7500.],
       [15564.],
       [ 8536.],
       [10192.],
       [ 9170.],
       [ 1869.],
       [ 8333.],
       [ 6120.],
       [ 3182.],
       [17242.],
       [12680.],
       [ 9060.],
       [ 4435.],
       [11613.],
       [ 8000.],
       [ 2160.],
       [ 9906.],
       [10206.],
       [ 8012.],
       [18261.],
       [ 8172.],
       [10890.],
       [ 7518.],
       [ 4426.],
       [ 8872.],
       [ 6155.],
       [ 9000.],
       [ 9101.],
       [ 8765.],
       [21750.],
       [ 7200.],
       [11235.],
       [10240.],
       [ 8125.],
       [16492.],
       [ 9317.],
       [ 9920.],
       [ 7903.],
       [ 8089.],
       [ 8487.],
       [ 9144.],
       [13837.],
       [ 9525.],
       [ 3068.],
       [ 2280.],
       [ 7875.],
       [ 8127.],
       [ 9060.],
       [ 8396.],
       [12046.],
       [ 9724.],
       [ 8366.],
       [ 9928.],
       [ 4060.

In [20]:
X_train

MSSubClass  LotArea LotConfig BldgType  OverallCond  YearBuilt  \
1173          50    18030    Inside     1Fam            6       1946   
898           20    12919    Inside     1Fam            5       2009   
1364         160     3180    Inside   TwnhsE            5       2005   
563           50    21780    Inside     1Fam            7       1918   
2208          20    26073   CulDSac     1Fam            5       1956   
...          ...      ...       ...      ...          ...        ...   
763           60     9430    Inside     1Fam            5       1999   
835           20     9600    Inside     1Fam            7       1950   
1653         160     2308       FR2   TwnhsE            5       1976   
2607          20    33983    Inside     1Fam            6       1977   
2732          20     9600    Inside     1Fam            6       1961   

      YearRemodAdd Exterior1st  BsmtFinSF2  TotalBsmtSF  
1173          1994     MetalSd       469.0       1598.0  
898           2010     VinylSd         0.0       2330.0  
1364          2005     MetalSd         0.0        600.0  
563           1950     Wd Sdng         0.0       1163.0  
2208          1956     BrkFace         0.0       1898.0  
...            ...         ...         ...          ...  
763           1999     VinylSd         0.0       1252.0  
835           1995     VinylSd         0.0       1067.0  
1653          1976     Plywood         0.0        804.0  
2607          1994     Plywood         0.0       1160.0  
2732          1990     WdShing         0.0       1251.0  

[2335 rows x 10 columns]

In [21]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['1Fam', 'TwnhsE','Duplex','Twnhs','2fmCon']])
X_train_Bldg = oe.fit_transform(X_train[['BldgType']])
X_test_Bldg = oe.fit_transform(X_test[['BldgType']])


In [22]:
X_train_Bldg
# X_test_Bldg

array([[0.],
       [0.],
       [1.],
       ...,
       [1.],
       [0.],
       [0.]])

In [23]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder(drop='first',sparse_output=False)
X_train_lc_ext = oe.fit_transform(X_train[['LotConfig', 'Exterior1st']])
X_test_lc_ext = oe.fit_transform(X_test[['LotConfig', 'Exterior1st']])


In [24]:
X_train_lc_ext
X_test_lc_ext

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
X_train_MSC = X_train.drop(columns = ['LotArea','LotConfig','BldgType','OverallCond','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_MSC = X_test.drop(columns = ['LotArea','LotConfig','BldgType','OverallCond','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_MSC 

array([[ 50],
       [ 20],
       [160],
       ...,
       [160],
       [ 20],
       [ 20]], dtype=int64)

In [26]:
X_train_OC = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_OC = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_OC

array([[6],
       [5],
       [5],
       ...,
       [5],
       [6],
       [6]], dtype=int64)

In [27]:
X_train_YB = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_YB = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_YB

array([[1946],
       [2009],
       [2005],
       ...,
       [1976],
       [1977],
       [1961]], dtype=int64)

In [28]:
X_train_YRA = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_YRA = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_YRA

array([[1994],
       [2010],
       [2005],
       ...,
       [1976],
       [1994],
       [1990]], dtype=int64)

In [29]:
X_train_BSMT = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2']).values
X_test_BSMT = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2']).values
X_train_BSMT

array([[1598.],
       [2330.],
       [ 600.],
       ...,
       [ 804.],
       [1160.],
       [1251.]])

In [30]:
X_train_BSMT2 = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','TotalBsmtSF']).values
X_test_BSMT2 = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','TotalBsmtSF']).values
X_train_BSMT2

array([[469.],
       [  0.],
       [  0.],
       ...,
       [  0.],
       [  0.],
       [  0.]])

In [31]:
X_train

MSSubClass  LotArea LotConfig BldgType  OverallCond  YearBuilt  \
1173          50    18030    Inside     1Fam            6       1946   
898           20    12919    Inside     1Fam            5       2009   
1364         160     3180    Inside   TwnhsE            5       2005   
563           50    21780    Inside     1Fam            7       1918   
2208          20    26073   CulDSac     1Fam            5       1956   
...          ...      ...       ...      ...          ...        ...   
763           60     9430    Inside     1Fam            5       1999   
835           20     9600    Inside     1Fam            7       1950   
1653         160     2308       FR2   TwnhsE            5       1976   
2607          20    33983    Inside     1Fam            6       1977   
2732          20     9600    Inside     1Fam            6       1961   

      YearRemodAdd Exterior1st  BsmtFinSF2  TotalBsmtSF  
1173          1994     MetalSd       469.0       1598.0  
898           2010     VinylSd         0.0       2330.0  
1364          2005     MetalSd         0.0        600.0  
563           1950     Wd Sdng         0.0       1163.0  
2208          1956     BrkFace         0.0       1898.0  
...            ...         ...         ...          ...  
763           1999     VinylSd         0.0       1252.0  
835           1995     VinylSd         0.0       1067.0  
1653          1976     Plywood         0.0        804.0  
2607          1994     Plywood         0.0       1160.0  
2732          1990     WdShing         0.0       1251.0  

[2335 rows x 10 columns]

In [32]:
X_train_transformed = np.concatenate((X_train_MSC, X_train_Area,X_train_lc_ext , X_train_Bldg,
                                      X_train_OC,X_train_YB,X_train_YRA ,X_train_BSMT2, X_train_BSMT ), axis =1)

X_test_transformed = np.concatenate((X_test_MSC, X_test_Area, X_test_lc_ext , X_test_Bldg,
                                     X_test_OC, X_test_YB, X_test_YRA , X_test_BSMT2, X_test_BSMT ), axis =1)
X_train_transformed


array([[5.0000e+01, 1.8030e+04, 0.0000e+00, ..., 1.9940e+03, 4.6900e+02,
        1.5980e+03],
       [2.0000e+01, 1.2919e+04, 0.0000e+00, ..., 2.0100e+03, 0.0000e+00,
        2.3300e+03],
       [1.6000e+02, 3.1800e+03, 0.0000e+00, ..., 2.0050e+03, 0.0000e+00,
        6.0000e+02],
       ...,
       [1.6000e+02, 2.3080e+03, 0.0000e+00, ..., 1.9760e+03, 0.0000e+00,
        8.0400e+02],
       [2.0000e+01, 3.3983e+04, 0.0000e+00, ..., 1.9940e+03, 0.0000e+00,
        1.1600e+03],
       [2.0000e+01, 9.6000e+03, 0.0000e+00, ..., 1.9900e+03, 0.0000e+00,
        1.2510e+03]])

# Column Transformation 

In [33]:
from sklearn.compose import ColumnTransformer

In [34]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['LotArea']),
    ('tnf2',OrdinalEncoder(categories=[['1Fam', 'TwnhsE','Duplex','Twnhs','2fmCon']]),['BldgType']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['LotConfig', 'Exterior1st'])
],remainder='passthrough')


In [35]:
transformer.fit_transform(X_train)


array([[1.8030e+04, 0.0000e+00, 0.0000e+00, ..., 1.9940e+03, 4.6900e+02,
        1.5980e+03],
       [1.2919e+04, 0.0000e+00, 0.0000e+00, ..., 2.0100e+03, 0.0000e+00,
        2.3300e+03],
       [3.1800e+03, 1.0000e+00, 0.0000e+00, ..., 2.0050e+03, 0.0000e+00,
        6.0000e+02],
       ...,
       [2.3080e+03, 1.0000e+00, 0.0000e+00, ..., 1.9760e+03, 0.0000e+00,
        8.0400e+02],
       [3.3983e+04, 0.0000e+00, 0.0000e+00, ..., 1.9940e+03, 0.0000e+00,
        1.1600e+03],
       [9.6000e+03, 0.0000e+00, 0.0000e+00, ..., 1.9900e+03, 0.0000e+00,
        1.2510e+03]])