In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df = pd.read_csv('50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [4]:
df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [5]:
X= df.drop(columns='Profit')
y= df['Profit']

In [6]:
X = pd.get_dummies(data=X,columns=['State'],drop_first=True)

In [7]:
X.head()

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10          False            True
1  162597.70       151377.59        443898.53          False           False
2  153441.51       101145.55        407934.54           True           False
3  144372.41       118671.85        383199.62          False            True
4  142107.34        91391.77        366168.42           True           False

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [9]:
print('Shape of X_train is: ', X_train.shape)
print('Shape of X_test is: ', X_test.shape)
print('Shape of y_train is: ', y_train.shape)
print('Shape of y_test is: ', y_test.shape)


Shape of X_train is:  (35, 5)
Shape of X_test is:  (15, 5)
Shape of y_train is:  (35,)
Shape of y_test is:  (15,)


In [10]:
X_test

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
28   66051.52       182645.56        118148.20           True           False
11  100671.96        91790.61        249744.55          False           False
10  101913.08       110594.11        229160.95           True           False
41   27892.92        84710.77        164470.71           True           False
2   153441.51       101145.55        407934.54           True           False
27   72107.60       127864.55        353183.81          False            True
38   20229.59        65947.93        185265.10          False            True
31   61136.38       152701.92         88218.23          False            True
22   73994.56       122782.75        303319.26           True           False
4   142107.34        91391.77        366168.42           True           False
33   55493.95       103057.49        214634.81           True           False
35   46014.02        85047.44        205517.64          False            True
26   75328.87       144135.98        134050.07           True           False
34   46426.07       157693.92        210797.67          False           False
18   91749.16       114175.79        294919.57           True           False

In [11]:
y_test

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
33     96778.92
35     96479.51
26    105733.54
34     96712.80
18    124266.90
Name: Profit, dtype: float64

In [12]:
from sklearn. tree import DecisionTreeRegressor
dtreg = DecisionTreeRegressor()

In [13]:
dtreg.fit(X_train, y_train)

DecisionTreeRegressor()

In [14]:
y_pred = dtreg.predict(X_test)

In [15]:
y_pred

array([ 99937.59, 141585.52, 141585.52,  78239.91, 182901.99, 111313.02,
        81005.76, 101004.64, 118474.03, 156991.12, 107404.34,  89949.14,
       126992.93,  89949.14, 125370.37])

In [16]:
dtreg.predict([['653849.50','295615.23','987355.11','1','1']])

C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([192261.83])

In [17]:
train_acc = dtreg.predict(X_train)
train_acc

array([155752.6 , 132602.65,  64926.08,  35673.41, 101004.64, 129917.04,
        99937.59,  97427.84, 126992.93,  71498.49, 118474.03,  69758.98,
       152211.77, 134307.35, 107404.34, 156991.12, 125370.37,  78239.91,
        14681.4 , 191792.06, 141585.52,  89949.14, 108552.04, 156122.51,
       108733.99,  90708.19, 111313.02, 122776.86, 149759.96,  81005.76,
        49490.75, 182901.99, 192261.83,  42559.73,  65200.33])

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9335078042675485

In [19]:
r2_score(y_train,train_acc)

1.0