In [1]:
print("Hello world!")

Hello world!


## Numpy operations

In [2]:
import numpy as np

In [3]:
#add
arr1 = np.arange(1,21).reshape(5,4)
arr2 = np.arange(11,31).reshape(5,4)
#add = arr1 + arr2
add = np.add(arr1,arr2)
add

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50]])

In [4]:
#multiply
product = np.multiply(arr1, arr2)
#product = arr1 * arr2
product

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171, 200, 231, 264],
       [299, 336, 375, 416],
       [459, 504, 551, 600]])

In [5]:
#matrix multiplication
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(11,20).reshape(3,3)
final_arr = ar1.dot(ar2)
final_arr


array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [6]:
final_arr.max()

390

In [7]:
final_arr.min()

90

In [8]:
final_arr.std()

111.06754701531857

In [9]:
final_arr.mean()
final_arr.max(axis = 0)

array([342, 366, 390])

In [10]:
final_arr.argmax()

8

In [11]:
np.sqrt(final_arr)

array([[ 9.48683298,  9.79795897, 10.09950494],
       [14.69693846, 15.19868415, 15.68438714],
       [18.49324201, 19.13112647, 19.74841766]])

In [12]:
np.median(final_arr)

231.0

In [14]:
np.median(final_arr)

231.0

In [15]:
np.square(final_arr)

array([[  8100,   9216,  10404],
       [ 46656,  53361,  60516],
       [116964, 133956, 152100]])

In [16]:
np.exp(final_arr)

array([[1.22040329e+039, 4.92345829e+041, 1.98626484e+044],
       [6.42108015e+093, 2.09906226e+100, 6.86187098e+106],
       [3.37841355e+148, 8.94912093e+158, 2.37054357e+169]])

In [17]:
np.log(final_arr)

array([[4.49980967, 4.56434819, 4.62497281],
       [5.37527841, 5.44241771, 5.50533154],
       [5.83481074, 5.90263333, 5.96614674]])

In [18]:
np.log10(final_arr)

array([[1.95424251, 1.98227123, 2.00860017],
       [2.33445375, 2.36361198, 2.39093511],
       [2.53402611, 2.56348109, 2.59106461]])

# Slicing and indexing 

In [24]:
ar = np.arange(1,31).reshape(2,3,5)
ar

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [26]:
ar[0][0][1]

2

In [36]:
print(ar[1:])

[[[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [47]:
ar[0:1,:1,0:2]

array([[[1, 2]]])

In [51]:
ar[0:1]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [52]:
ar[0:1, 0:1,0:4]

array([[[1, 2, 3, 4]]])

In [54]:
ar.itemsize

4