## Random in python with numpy

In [1]:
import numpy as np
import random

In [2]:
a = np.random.randint(1,10,15).reshape(5,3)
a

array([[8, 4, 1],
       [8, 8, 2],
       [1, 2, 9],
       [1, 6, 3],
       [6, 3, 8]])

In [3]:
b = np.random.random(10)
b

array([0.04388849, 0.08844595, 0.16833519, 0.01128736, 0.42645995,
       0.06582571, 0.1708761 , 0.94999471, 0.82032362, 0.43531395])

In [4]:
c = np.random.random((3,3,3))
c

array([[[0.04954674, 0.47971539, 0.65001447],
        [0.84055615, 0.65042751, 0.3695709 ],
        [0.69699117, 0.95890341, 0.50475062]],

       [[0.78023396, 0.41038547, 0.43143829],
        [0.53668859, 0.03930606, 0.71254068],
        [0.49725983, 0.0912064 , 0.10299931]],

       [[0.45273842, 0.31304546, 0.86700351],
        [0.41295769, 0.43697485, 0.05964547],
        [0.82997365, 0.19508115, 0.89470738]]])

In [5]:
np.random.randint(1,10,(4,3))

array([[4, 5, 7],
       [7, 5, 5],
       [1, 1, 4],
       [3, 7, 1]])

In [6]:
np.random.randint(1,10,(2,4,3))

array([[[3, 6, 5],
        [7, 6, 9],
        [4, 7, 4],
        [6, 3, 6]],

       [[4, 2, 7],
        [7, 4, 5],
        [1, 7, 8],
        [7, 8, 6]]])

In [7]:
np.random.seed(20)
np.random.randint(1,2,30)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.random.rand(3)

array([0.5881308 , 0.89771373, 0.89153073])

In [9]:
np.random.rand(3,3,3)

array([[[0.81583748, 0.03588959, 0.69175758],
        [0.37868094, 0.51851095, 0.65795147],
        [0.19385022, 0.2723164 , 0.71860593]],

       [[0.78300361, 0.85032764, 0.77524489],
        [0.03666431, 0.11669374, 0.7512807 ],
        [0.23921822, 0.25480601, 0.85762553]],

       [[0.94977903, 0.56168686, 0.17878052],
        [0.77025193, 0.49238104, 0.63125307],
        [0.83949792, 0.4610394 , 0.49794007]]])

In [10]:
np.random.randn(3,3,3)

array([[[ 1.12013226,  1.33277821, -0.24333877],
        [-0.13003071, -0.10901737,  1.55618644],
        [ 0.12877835, -2.06694872, -0.88549315]],

       [[-1.10457948,  0.93286635,  2.059838  ],
        [-0.93493796, -1.61299022,  0.52706972],
        [-1.55110074,  0.32961334, -1.13652654]],

       [[-0.3384906 ,  0.32097078, -0.60230802],
        [ 1.54472836,  0.64703408,  0.59321721],
        [ 0.4380245 ,  1.35778902,  1.20451128]]])

 ## String operation, Comparison and Information

In [11]:
s1 = "HELLO there i'm using jupyter notebook. "
s2 = "Experience of using this is just great"

In [12]:
s= np.char.add(s1,s2)
s

array("HELLO there i'm using jupyter notebook. Experience of using this is just great",
      dtype='<U78')

In [13]:
np.char.multiply(s,3)

array("HELLO there i'm using jupyter notebook. Experience of using this is just greatHELLO there i'm using jupyter notebook. Experience of using this is just greatHELLO there i'm using jupyter notebook. Experience of using this is just great",
      dtype='<U234')

In [14]:
np.char.lower(s)

array("hello there i'm using jupyter notebook. experience of using this is just great",
      dtype='<U78')

In [15]:
np.char.center(s1,90)

array("                         HELLO there i'm using jupyter notebook.                          ",
      dtype='<U90')

In [16]:
np.char.split(s)

array(list(['HELLO', 'there', "i'm", 'using', 'jupyter', 'notebook.', 'Experience', 'of', 'using', 'this', 'is', 'just', 'great']),
      dtype=object)

In [17]:
s1 = "SMH"
s2 = "HMS"
s3 = "HSM"
s4 = np.char.join([":","/","-"],[s1,s2,s3])
s4

array(['S:M:H', 'H/M/S', 'H-S-M'], dtype='<U5')

In [18]:
s1 = "SMH"
s2 = "HMS"
s3 = "HSM"
s4 = np.char.join([":","/","-"],[s1,s1,s1])
s4

array(['S:M:H', 'S/M/H', 'S-M-H'], dtype='<U5')

In [19]:
s1 = "HELLO there i'm using jupyter notebook. "
np.char.replace(s1, "e" ,"E")

array("HELLO thErE i'm using jupytEr notEbook. ", dtype='<U40')

In [20]:
np.char.find(s1,"i")

array(12)

In [21]:
s1 = "HELLO there i'm using jupyter notebook. "
i = input("Enter you alphabet to check in string ")
if i in s1:
    c = np.char.index(s1,i)
    print(len(s1))
    print(c) 
else:
    print("Not Awailable")

Enter you alphabet to check in string  t


40
6


# Broadcasting

In [22]:
a = np.random.randint(1,10,10)
b = np.random.randint(1,10,10)
a

array([1, 6, 7, 8, 5, 1, 7, 2, 7, 8])

In [23]:
a+b

array([ 9, 13, 16, 17,  8,  4,  9,  8, 10, 16])

In [24]:
a[2]+2

9

In [25]:
a.ndim,b.ndim

(1, 1)

In [26]:
a.shape,b.shape

((10,), (10,))

In [27]:
a = np.ones((10))
c = a+b.T
c

array([ 9.,  8., 10., 10.,  4.,  4.,  3.,  7.,  4.,  9.])

In [28]:
np.ravel(c)

array([ 9.,  8., 10., 10.,  4.,  4.,  3.,  7.,  4.,  9.])

In [29]:
np.reshape(c,(5,2))

array([[ 9.,  8.],
       [10., 10.],
       [ 4.,  4.],
       [ 3.,  7.],
       [ 4.,  9.]])

In [30]:
a = np.ones((3,3,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
b = np.random.randint(1,10,12).reshape(4,3)
c = np.random.randint(1,10,12).reshape(4,3)

In [33]:
np.multiply(b,c)

array([[ 7, 42, 30],
       [25,  6, 45],
       [48,  8, 24],
       [ 8, 15, 20]])

In [34]:
b*c

array([[ 7, 42, 30],
       [25,  6, 45],
       [48,  8, 24],
       [ 8, 15, 20]])

In [37]:
z = (b*c).T
z

array([[ 7, 25, 48,  8],
       [42,  6,  8, 15],
       [30, 45, 24, 20]])

In [43]:
z.flatten()

array([ 7, 25, 48,  8, 42,  6,  8, 15, 30, 45, 24, 20])

In [44]:
z.ravel()

array([ 7, 25, 48,  8, 42,  6,  8, 15, 30, 45, 24, 20])

In [45]:
np.ravel(z)

array([ 7, 25, 48,  8, 42,  6,  8, 15, 30, 45, 24, 20])