In [4]:
import numpy as np

In [5]:
# 0-D Array
arr1 = np.array(3)
print(arr1)

3


In [6]:
#1-D array
arr2 = np. array([2,3,4,5])
print(arr2)

[2 3 4 5]


In [8]:
# 2-D Array
arr3 = np.array([[2,3,4,5],[3,2,4,2]])
print(arr3)

[[2 3 4 5]
 [3 2 4 2]]


In [14]:
# 3-D Array
arr4 = np.array([[[2,3,4,5],[4,3,5,7]],[[2,3,4,5],[4,3,5,7]],[[4,3,5,7],[5,4,3,5]]])
print(arr4)

[[[2 3 4 5]
  [4 3 5 7]]

 [[2 3 4 5]
  [4 3 5 7]]

 [[4 3 5 7]
  [5 4 3 5]]]


In [16]:
arr4 = arr4+10
print(arr4)

[[[12 13 14 15]
  [14 13 15 17]]

 [[12 13 14 15]
  [14 13 15 17]]

 [[14 13 15 17]
  [15 14 13 15]]]


In [36]:
print(arr4.ndim)

3


In [37]:
arr4.dtype

dtype('int32')

In [17]:
arr4 = arr4*2
print(arr4)

[[[24 26 28 30]
  [28 26 30 34]]

 [[24 26 28 30]
  [28 26 30 34]]

 [[28 26 30 34]
  [30 28 26 30]]]


In [21]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

mat3 = np.dot(mat1, mat2) #Multiplication of matrices using dot method
print(mat3)


mat4 = mat1 @ mat2     #Multiplication of matrices using @ keyword
print(mat4)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [28]:
# Slicing and indexing of an array
print(mat1[0,1])  # indexing
print(mat1[0:])   #Slicing

2
[[1 2]
 [3 4]]


In [43]:
ones_arr = np.ones([3,3])
print(ones_arr)

zeros_arr = np.zeros([3,4])
zeros_arr

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
# linspace - generates numbers evenly spaced over a specified interval
arrr1 = np.linspace(0, 10, 9)
print(arrr) 

arange_ar = np.arange(0, 10, 2)
print(arange_ar)


(array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ]), 1.25)
[0 2 4 6 8]


In [53]:
arrr2 = np.linspace(0, 10, 9,endpoint = False,retstep=False)
print(arrr)  


(array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ]), 1.25)


In [54]:
arrr3 = np.linspace(0, 10, 9,endpoint = True,retstep=True)
print(arrr)  

(array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ]), 1.25)


In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(arr)


flattened_arr = arr.flatten()
print("Flattened Array:")
print(flattened_arr)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(arr)


flattened_arr = arr.flatten(order = 'f')
print("Flattened Array:")
print(flattened_arr)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array:
[1 4 7 2 5 8 3 6 9]


In [78]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(arr)


flattened_arr = arr.flatten(order = 'k')
print("Flattened Array:")
print(flattened_arr)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [87]:
flattened_arr=flattened_arr.transpose()
print(flattened_arr)

[1 2 3 4 5 6 7 8 9]


In [88]:
flattened_arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# sum of all elements
arr1 = np.array([4,5,9,3,7,0,3,6])
sum_value = np.sum(arr1)
print("The sum of all elements: ",sum_value) 

# mean of all elements
mean_value = np.mean(arr1)
print("The mean of all elements: ",mean_value)  

# maximum and minimum values
max_value = np.max(arr1)
min_value = np.min(arr1)
print("maximum value: ",max_value)  
print("minimum value: ",min_value)  

# standard deviation
std_value = np.std(arr1)
print("The standard deviation of all elements: ",std_value)  


The sum of all elements:  37
The mean of all elements:  4.625
maximum value:  9
minimum value:  0
The standard deviation of all elements:  2.595067436503337


In [21]:
shape = input("Enter the shape of array i.e., 2 X 2 = 2 2 ").split()
inp = input("Enter Your numbers with a space between two numbers ").split()
arr = np.array([int(i) for i in inp]).reshape(tuple(map(int, shape)))
print(arr)
#print(arr.ravel())
print(arr.reshape(2,3))

Enter the shape of array i.e., 2 X 2 = 2 2  3 2
Enter Your numbers with a space between two numbers  2 3 4 5 2 3


[[2 3]
 [4 5]
 [2 3]]
[[2 3 4]
 [5 2 3]]
